name = "Robot Recolector"

# Dejamos esto vac√≠o para que no busque en PyPI
packages = []

[[fetch]]
files = [
    "main.py",
    "herramientas.py",
    "interfaz/botones.py",
    "assets/sprites/robot_img.png",
    "assets/sprites/enemy_img.png",
    "assets/sprites/battery_img.png",
    "assets/sprites/door.png",
    "assets/tiles/floor.png",
    "assets/tiles/plataform.png",
    "assets/sounds/jump.mp3",
    "assets/sounds/gameover.mp3",
    "assets/sounds/powerup.mp3",
    "assets/sounds/victory.mp3",
    "assets/sounds/music.mp3"
]
