name = "Robot Recolector"
description = "Juego para mi novia"

# Cargamos Pygame (la versión optimizada para web)
packages = ["pygame-ce"]

# LISTA AQUÍ TODOS TUS ARCHIVOS
# Esto es crítico: si falta una imagen, el juego no arranca
files = ["main.py", "assets/robot.png", "assets/fondo.png"]
